### PR TITLE
Add ability to filter schedule by event types

### PR DESCRIPTION
**Pull request by trgardos**
I added the ability to filter by event type on the schedule page in DS701.  Adding here too.

I suggest you test it out locally to make sure it works, but it should.

Created issue #2 to reference this.

### CODE REVIEW

**Comment by jconsidi** [comment]
I tried it locally and got the checkboxes, but they didn't seem to do anything. I'll poke at it later.

**Comment by trgardos** [comment]
Did the page finish loading? Something was happening for me today that the pages took a while to load  and then they worked.
________________________________

**Comment by trgardos** [comment]
@jconsidi -- a student found the issue. It was using a JS package that was deprecated. Just pushed the fix. Should be all good now.

**Comment by trgardos** [comment]
> @jconsidi -- a student found the issue. It was using a JS package that was deprecated. Just pushed the fix. Should be all good now.

@XThomasBU , @jconsidi  -- i suggest you merge this PR to fix your page loading issue.

**Pull request merged**
